# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
# relative_permalinks: true

# Setup
title:               IEEE Student Branch
tagline:             'Student Branch of the Univerity of Brescia'
description:         'The offical site of the STB01019'
url:                 https://ieee-brescia.github.io/
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Nik Vinter
  url:               github.com/thevinter
  email:             nikita.brancatisano@ieee.org

# Custom vars
version:             1.0.0
